version: '3.9'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: &PG_DBNAME concourse
      POSTGRES_PASSWORD: &PG_PASSWORD concourse_pass
      POSTGRES_USER: &PG_USER concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse:7.9.1-ubuntu
    platform: linux/amd64
    command: quickstart
    privileged: true
    depends_on:
      - concourse-db
    ports:
      - "8080:8080"
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: *PG_USER
      CONCOURSE_POSTGRES_PASSWORD: *PG_PASSWORD
      CONCOURSE_POSTGRES_DATABASE: *PG_DBNAME
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: ptfe:ptfe
      CONCOURSE_MAIN_TEAM_LOCAL_USER: ptfe
      CONCOURSE_WORKER_SWEEP_INTERVAL: 24h
      # If running on a non M1/M2 MacOS, optionally change this to overlay
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: naive
      CONCOURSE_WORKER_BAGGAGECLAIM_DISABLE_USER_NAMESPACES: true
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      CONCOURSE_X_FRAME_OPTIONS: allow
      CONCOURSE_CONTENT_SECURITY_POLICY: "*"
      CONCOURSE_CLUSTER_NAME: PTFE
      CONCOURSE_WORKER_WORK_DIR: /worker-state
      # If running on a non M1/M2 MacOS, optionally change this to guardian (default) or containerd (if cgroupsv2 is supported by the host)
      CONCOURSE_WORKER_RUNTIME: "houdini"






# version: '3'

# services:
#   concourse-db:
#     image: postgres
#     environment:
#       POSTGRES_DB: concourse
#       POSTGRES_PASSWORD: concourse_pass
#       POSTGRES_USER: concourse_user
#       PGDATA: /database

#   concourse:
#     image: concourse/concourse
#     command: quickstart
#     privileged: true
#     depends_on: [concourse-db]
#     ports: ["8080:8080"]
#     environment:
#       CONCOURSE_POSTGRES_HOST: concourse-db
#       CONCOURSE_POSTGRES_USER: concourse_user
#       CONCOURSE_POSTGRES_PASSWORD: concourse_pass
#       CONCOURSE_POSTGRES_DATABASE: concourse
#       CONCOURSE_EXTERNAL_URL: http://localhost:8080
#       CONCOURSE_ADD_LOCAL_USER: test:test
#       CONCOURSE_MAIN_TEAM_LOCAL_USER: test
#       # instead of relying on the default "detect"
#       CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
#       CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
#       CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
#       CONCOURSE_X_FRAME_OPTIONS: allow
#       CONCOURSE_CONTENT_SECURITY_POLICY: "*"
#       CONCOURSE_CLUSTER_NAME: tutorial
#       CONCOURSE_WORKER_CONTAINERD_DNS_SERVER: "8.8.8.8"
#       # For ARM-based machine, change the Concourse runtime to "houdini"
#       CONCOURSE_WORKER_RUNTIME: "containerd"









# version: '3'

# services:
#   db:
#     image: postgres
#     environment:
#       POSTGRES_DB: concourse
#       POSTGRES_USER: concourse_user
#       POSTGRES_PASSWORD: concourse_pass
#     logging:
#       driver: "json-file"
#       options:
#         max-file: "5"
#         max-size: "10m"

#   web:
#     image: concourse/concourse
#     command: web
#     links: [db]
#     depends_on: [db]
#     ports: ["8080:8080"]
#     volumes: ["./keys/web:/concourse-keys"]
#     environment:
#       CONCOURSE_EXTERNAL_URL: http://localhost:8080
#       CONCOURSE_POSTGRES_HOST: db
#       CONCOURSE_POSTGRES_USER: concourse_user
#       CONCOURSE_POSTGRES_PASSWORD: concourse_pass
#       CONCOURSE_POSTGRES_DATABASE: concourse
#       CONCOURSE_ADD_LOCAL_USER: test:test
#       CONCOURSE_MAIN_TEAM_LOCAL_USER: test
#     logging:
#       driver: "json-file"
#       options:
#         max-file: "5"
#         max-size: "10m"

#   worker:
#     image: concourse/concourse
#     command: worker
#     privileged: true
#     depends_on: [web]
#     volumes: ["./keys/worker:/concourse-keys"]
#     links: [web]
#     stop_signal: SIGUSR2
#     environment:
#       CONCOURSE_TSA_HOST: web:2222
#       # enable DNS proxy to support Docker's 127.x.x.x DNS server
#       CONCOURSE_GARDEN_DNS_PROXY_ENABLE: "true"
#     logging:
#       driver: "json-file"
#       options:
#         max-file: "5"
#         max-size: "10m"